// Generated by dts-bundle v0.7.3

declare module '@utkusarioglu/mixer' {
    export const Parent: (extender_class?: any) => MixinBuilder;
    class MixinBuilder {
        constructor(extender_class?: any);
        with(...mixins: any[]): any;
    }
    export {};
}

