// Generated by dts-bundle v0.7.3

declare module '@utkusarioglu/mixer' {
    export { Parent } from "@utkusarioglu/mixer/mixer";
    export { Constructor } from "@utkusarioglu/mixer/t_mixer";
}

declare module '@utkusarioglu/mixer/mixer' {
    export const Parent: (extender_class?: any) => MixinBuilder;
    class MixinBuilder {
        constructor(extender_class?: any);
        with(...mixins: any[]): any;
    }
    export {};
}

declare module '@utkusarioglu/mixer/t_mixer' {
    export type Constructor<T = {}> = new (...args: any[]) => T;
}

